services:
  ladlemethis:
    image: ladlemethis
    build:
      context: .
      dockerfile: LadleMeThis/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DbConnectionString=${DbConnectionString}
  db:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: ladlemethis_db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${DB_PASSWORD}
    ports:
      - "1433:1433"
