import "./globals.scss";
import Navbar from "@/src/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="layout">
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
