import "./globals.scss";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
import { ToastProvider } from "@/context/ToastContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="layout">
        <ToastProvider>
        <Navbar />
          {children}
        </ToastProvider>
        <Footer />
      </body>
    </html>
  );
}
